# Generated by Django 5.2.4 on 2025-08-02 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'تسجيل دخول'), ('game_created', 'إنشاء لعبة'), ('game_joined', 'انضمام للعبة'), ('game_completed', 'إتمام لعبة'), ('package_purchased', 'شراء حزمة'), ('profile_updated', 'تحديث الملف الشخصي')], max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('game_type', models.CharField(blank=True, max_length=20, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_team1_name', models.CharField(default='الفريق الأخضر', max_length=50)),
                ('default_team2_name', models.CharField(default='الفريق البرتقالي', max_length=50)),
                ('auto_start_timer', models.BooleanField(default=True)),
                ('show_answers_immediately', models.BooleanField(default=False)),
                ('sound_enabled', models.BooleanField(default=True)),
                ('volume_level', models.IntegerField(default=50)),
                ('theme_preference', models.CharField(choices=[('light', 'فاتح'), ('dark', 'غامق'), ('auto', 'تلقائي')], default='light', max_length=20)),
                ('quick_mode_enabled', models.BooleanField(default=False)),
                ('show_statistics', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('is_host', models.BooleanField(default=True)),
                ('host_name', models.CharField(blank=True, max_length=50, null=True)),
                ('total_games_hosted', models.IntegerField(default=0)),
                ('total_games_played', models.IntegerField(default=0)),
                ('favorite_game', models.CharField(blank=True, choices=[('letters', 'خلية الحروف'), ('images', 'تحدي الصور'), ('quiz', 'سؤال وجواب')], max_length=20, null=True)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=False)),
                ('account_type', models.CharField(choices=[('free', 'مجاني'), ('premium', 'مميز')], default='free', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
