# Generated by Django 5.2.4 on 2025-08-02 23:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('game_type', models.CharField(choices=[('letters', 'خلية الحروف'), ('images', 'تحدي الصور'), ('quiz', 'سؤال وجواب')], max_length=20)),
                ('package_number', models.IntegerField()),
                ('is_free', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['game_type', 'package_number'],
                'unique_together': {('game_type', 'package_number')},
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('game_type', models.CharField(choices=[('letters', 'خلية الحروف'), ('images', 'تحدي الصور'), ('quiz', 'سؤال وجواب')], max_length=20)),
                ('team1_name', models.CharField(default='الفريق الأخضر', max_length=50)),
                ('team2_name', models.CharField(default='الفريق البرتقالي', max_length=50)),
                ('team1_score', models.IntegerField(default=0)),
                ('team2_score', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('winner_team', models.CharField(blank=True, choices=[('team1', 'الفريق الأول'), ('team2', 'الفريق الثاني'), ('draw', 'تعادل')], max_length=10, null=True)),
                ('display_link', models.CharField(max_length=100, unique=True)),
                ('contestants_link', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.gamepackage')),
            ],
        ),
        migrations.CreateModel(
            name='LettersGameProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_states', models.JSONField(default=dict)),
                ('used_letters', models.JSONField(default=list)),
                ('current_letter', models.CharField(blank=True, max_length=1, null=True)),
                ('current_question_type', models.CharField(default='main', max_length=10)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='letters_progress', to='games.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('team', models.CharField(choices=[('team1', 'الفريق الأول'), ('team2', 'الفريق الثاني')], max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contestants', to='games.gamesession')),
            ],
            options={
                'unique_together': {('session', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LettersGameQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1)),
                ('question_type', models.CharField(choices=[('main', 'رئيسي'), ('alt1', 'بديل 1'), ('alt2', 'بديل 2')], default='main', max_length=10)),
                ('question', models.TextField()),
                ('answer', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters_questions', to='games.gamepackage')),
            ],
            options={
                'unique_together': {('package', 'letter', 'question_type')},
            },
        ),
        migrations.CreateModel(
            name='UserPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('games_played', models.IntegerField(default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.gamepackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'package')},
            },
        ),
    ]
