# Generated by Django 5.2.4 on 2025-08-03 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contestant',
            options={'ordering': ['team', 'name'], 'verbose_name': 'متسابق', 'verbose_name_plural': 'المتسابقون'},
        ),
        migrations.AlterModelOptions(
            name='gamepackage',
            options={'ordering': ['game_type', 'package_number'], 'verbose_name': 'حزمة لعبة', 'verbose_name_plural': 'حزم الألعاب'},
        ),
        migrations.AlterModelOptions(
            name='gamesession',
            options={'ordering': ['-created_at'], 'verbose_name': 'جلسة لعب', 'verbose_name_plural': 'جلسات اللعب'},
        ),
        migrations.AlterModelOptions(
            name='lettersgameprogress',
            options={'verbose_name': 'تقدم لعبة الحروف', 'verbose_name_plural': 'تقدم ألعاب الحروف'},
        ),
        migrations.AlterModelOptions(
            name='lettersgamequestion',
            options={'ordering': ['letter', 'question_type'], 'verbose_name': 'سؤال خلية حروف', 'verbose_name_plural': 'أسئلة خلية الحروف'},
        ),
        migrations.AlterModelOptions(
            name='userpurchase',
            options={'ordering': ['-purchase_date'], 'verbose_name': 'مشترى حزمة', 'verbose_name_plural': 'مشتريات الحزم'},
        ),
        migrations.AlterField(
            model_name='contestant',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط؟'),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانضمام'),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='name',
            field=models.CharField(max_length=50, verbose_name='اسم المتسابق'),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contestants', to='games.gamesession', verbose_name='الجلسة'),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='team',
            field=models.CharField(choices=[('team1', 'الفريق الأول'), ('team2', 'الفريق الثاني')], max_length=10, verbose_name='الفريق'),
        ),
        migrations.AlterField(
            model_name='gamepackage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='gamepackage',
            name='game_type',
            field=models.CharField(choices=[('letters', 'خلية الحروف'), ('images', 'تحدي الصور'), ('quiz', 'سؤال وجواب')], help_text='اختر نوع اللعبة', max_length=20, verbose_name='نوع اللعبة'),
        ),
        migrations.AlterField(
            model_name='gamepackage',
            name='is_active',
            field=models.BooleanField(default=True, help_text='هل الحزمة متاحة للشراء؟', verbose_name='فعالة؟'),
        ),
        migrations.AlterField(
            model_name='gamepackage',
            name='is_free',
            field=models.BooleanField(default=False, help_text='هل هذه الحزمة مجانية؟', verbose_name='مجانية؟'),
        ),
        migrations.AlterField(
            model_name='gamepackage',
            name='package_number',
            field=models.IntegerField(help_text='رقم الحزمة (1، 2، 3...)', verbose_name='رقم الحزمة'),
        ),
        migrations.AlterField(
            model_name='gamepackage',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='سعر الحزمة بالريال السعودي', max_digits=10, verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='contestants_link',
            field=models.CharField(help_text='رابط صفحة المتسابقين', max_length=100, unique=True, verbose_name='رابط المتسابقين'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='display_link',
            field=models.CharField(help_text='رابط شاشة العرض للجمهور', max_length=100, unique=True, verbose_name='رابط العرض'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='game_type',
            field=models.CharField(choices=[('letters', 'خلية الحروف'), ('images', 'تحدي الصور'), ('quiz', 'سؤال وجواب')], max_length=20, verbose_name='نوع اللعبة'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='host',
            field=models.ForeignKey(help_text='الشخص الذي ينظم اللعبة', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المقدم'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='is_active',
            field=models.BooleanField(default=True, help_text='هل الجلسة نشطة حالياً؟', verbose_name='نشطة؟'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='هل انتهت الجلسة؟', verbose_name='مكتملة؟'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.gamepackage', verbose_name='الحزمة'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='team1_name',
            field=models.CharField(default='الفريق الأخضر', max_length=50, verbose_name='اسم الفريق الأول'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='team1_score',
            field=models.IntegerField(default=0, verbose_name='نقاط الفريق الأول'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='team2_name',
            field=models.CharField(default='الفريق البرتقالي', max_length=50, verbose_name='اسم الفريق الثاني'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='team2_score',
            field=models.IntegerField(default=0, verbose_name='نقاط الفريق الثاني'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='winner_team',
            field=models.CharField(blank=True, choices=[('team1', 'الفريق الأول'), ('team2', 'الفريق الثاني'), ('draw', 'تعادل')], max_length=10, null=True, verbose_name='الفريق الفائز'),
        ),
        migrations.AlterField(
            model_name='lettersgameprogress',
            name='cell_states',
            field=models.JSONField(default=dict, help_text='حالة كل خلية في الشبكة', verbose_name='حالة الخلايا'),
        ),
        migrations.AlterField(
            model_name='lettersgameprogress',
            name='current_letter',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='الحرف الحالي'),
        ),
        migrations.AlterField(
            model_name='lettersgameprogress',
            name='current_question_type',
            field=models.CharField(default='main', max_length=10, verbose_name='نوع السؤال الحالي'),
        ),
        migrations.AlterField(
            model_name='lettersgameprogress',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='letters_progress', to='games.gamesession', verbose_name='الجلسة'),
        ),
        migrations.AlterField(
            model_name='lettersgameprogress',
            name='used_letters',
            field=models.JSONField(default=list, help_text='قائمة الحروف التي تم استخدامها', verbose_name='الحروف المستخدمة'),
        ),
        migrations.AlterField(
            model_name='lettersgamequestion',
            name='answer',
            field=models.CharField(help_text='الإجابة الصحيحة', max_length=100, verbose_name='الإجابة'),
        ),
        migrations.AlterField(
            model_name='lettersgamequestion',
            name='category',
            field=models.CharField(help_text='تصنيف السؤال (بلدان، وظائف، حيوانات...)', max_length=50, verbose_name='التصنيف'),
        ),
        migrations.AlterField(
            model_name='lettersgamequestion',
            name='letter',
            field=models.CharField(help_text='الحرف العربي (أ، ب، ت...)', max_length=1, verbose_name='الحرف'),
        ),
        migrations.AlterField(
            model_name='lettersgamequestion',
            name='package',
            field=models.ForeignKey(help_text='اختر حزمة خلية الحروف', on_delete=django.db.models.deletion.CASCADE, related_name='letters_questions', to='games.gamepackage', verbose_name='الحزمة'),
        ),
        migrations.AlterField(
            model_name='lettersgamequestion',
            name='question',
            field=models.TextField(help_text='نص السؤال كاملاً', verbose_name='السؤال'),
        ),
        migrations.AlterField(
            model_name='lettersgamequestion',
            name='question_type',
            field=models.CharField(choices=[('main', 'رئيسي'), ('alt1', 'بديل أول'), ('alt2', 'بديل ثاني')], default='main', help_text='نوع السؤال (رئيسي أم بديل)', max_length=10, verbose_name='نوع السؤال'),
        ),
        migrations.AlterField(
            model_name='userpurchase',
            name='games_played',
            field=models.IntegerField(default=0, help_text='عدد المرات التي لعب فيها', verbose_name='عدد الألعاب'),
        ),
        migrations.AlterField(
            model_name='userpurchase',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='هل انتهى المستخدم من اللعب؟', verbose_name='مكتملة؟'),
        ),
        migrations.AlterField(
            model_name='userpurchase',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.gamepackage', verbose_name='الحزمة'),
        ),
        migrations.AlterField(
            model_name='userpurchase',
            name='purchase_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الشراء'),
        ),
        migrations.AlterField(
            model_name='userpurchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
