# Generated by Django 5.2.4 on 2025-08-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_contestant_options_alter_gamepackage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lettersgameprogress',
            name='current_letter',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='الحرف الحالي'),
        ),
        migrations.AlterField(
            model_name='lettersgamequestion',
            name='letter',
            field=models.CharField(help_text='الحرف العربي (أ، ب، ت...)', max_length=3, verbose_name='الحرف'),
        ),
    ]
