# Generated by Django 5.2.4 on 2025-08-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_lettersgameprogress_current_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepackage',
            name='description',
            field=models.TextField(blank=True, help_text='وصف قصير للحزمة يظهر للمستخدمين', verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='gamepackage',
            name='question_theme',
            field=models.CharField(choices=[('mixed', 'متنوعة'), ('sports', 'رياضية')], default='mixed', help_text='مثال: متنوعة، رياضية', max_length=20, verbose_name='نوع الأسئلة'),
        ),
    ]
