# Generated by Django 5.2.4 on 2025-08-12 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_gamepackage_description_gamepackage_question_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesPackage',
            fields=[
            ],
            options={
                'verbose_name': 'حزمة - تحدي الصور',
                'verbose_name_plural': 'حزم - تحدي الصور',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('games.gamepackage',),
        ),
        migrations.CreateModel(
            name='ImagesSession',
            fields=[
            ],
            options={
                'verbose_name': 'جلسة - تحدي الصور',
                'verbose_name_plural': 'جلسات - تحدي الصور',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('games.gamesession',),
        ),
        migrations.CreateModel(
            name='LettersPackage',
            fields=[
            ],
            options={
                'verbose_name': 'حزمة - خلية الحروف',
                'verbose_name_plural': 'حزم - خلية الحروف',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('games.gamepackage',),
        ),
        migrations.CreateModel(
            name='LettersSession',
            fields=[
            ],
            options={
                'verbose_name': 'جلسة - خلية الحروف',
                'verbose_name_plural': 'جلسات - خلية الحروف',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('games.gamesession',),
        ),
        migrations.CreateModel(
            name='QuizPackage',
            fields=[
            ],
            options={
                'verbose_name': 'حزمة - سؤال وجواب',
                'verbose_name_plural': 'حزم - سؤال وجواب',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('games.gamepackage',),
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
            ],
            options={
                'verbose_name': 'جلسة - سؤال وجواب',
                'verbose_name_plural': 'جلسات - سؤال وجواب',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('games.gamesession',),
        ),
    ]
