# Generated by Django 5.2.4 on 2025-08-13 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_imagespackage_imagessession_letterspackage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lettersgamequestion',
            name='question_type',
            field=models.CharField(choices=[('main', 'رئيسي'), ('alt1', 'بديل أول'), ('alt2', 'بديل ثاني'), ('alt3', 'بديل ثالث'), ('alt4', 'بديل رابع')], default='main', help_text='نوع السؤال (رئيسي أم بديل)', max_length=10, verbose_name='نوع السؤال'),
        ),
    ]
