# Generated by Django 5.2.4 on 2025-08-14 14:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_lettersgamequestion_question_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userpurchase',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userpurchase',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='وقت انتهاء صلاحية الشراء (يُحدَّد تلقائيًا إلى 72 ساعة بعد الشراء)', null=True, verbose_name='ينتهي في'),
        ),
        migrations.AlterField(
            model_name='userpurchase',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='هل انتهى المستخدم من الاستخدام/اللعب على هذه الحزمة؟', verbose_name='مكتملة؟'),
        ),
        migrations.AddIndex(
            model_name='userpurchase',
            index=models.Index(fields=['user', 'package'], name='games_userp_user_id_6e1898_idx'),
        ),
        migrations.AddIndex(
            model_name='userpurchase',
            index=models.Index(fields=['is_completed'], name='games_userp_is_comp_c38af4_idx'),
        ),
        migrations.AddIndex(
            model_name='userpurchase',
            index=models.Index(fields=['expires_at'], name='games_userp_expires_200431_idx'),
        ),
        migrations.AddConstraint(
            model_name='userpurchase',
            constraint=models.UniqueConstraint(condition=models.Q(('is_completed', False)), fields=('user', 'package'), name='unique_active_purchase_per_package'),
        ),
    ]
