# Generated by Django 5.2.4 on 2025-08-16 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_alter_userpurchase_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepackage',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='السعر بعد الخصم (اختياري)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='gamepackage',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='السعر الأصلي قبل الخصم', max_digits=10, null=True),
        ),
    ]
