# Generated by Django 5.2.4 on 2025-08-16 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_gamepackage_discounted_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='host',
            field=models.ForeignKey(blank=True, help_text='الشخص الذي ينظم اللعبة (قد تكون فارغة)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المقدم'),
        ),
        migrations.AddIndex(
            model_name='contestant',
            index=models.Index(fields=['session', 'team'], name='games_conte_session_8b343a_idx'),
        ),
        migrations.AddIndex(
            model_name='gamepackage',
            index=models.Index(fields=['game_type', 'is_active'], name='games_gamep_game_ty_240c2a_idx'),
        ),
        migrations.AddIndex(
            model_name='gamepackage',
            index=models.Index(fields=['is_free'], name='games_gamep_is_free_5ad299_idx'),
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['game_type', 'created_at'], name='games_games_game_ty_28ffe6_idx'),
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['is_active'], name='games_games_is_acti_d384cc_idx'),
        ),
        migrations.AddIndex(
            model_name='lettersgamequestion',
            index=models.Index(fields=['package', 'letter'], name='games_lette_package_90516e_idx'),
        ),
        migrations.AddIndex(
            model_name='lettersgamequestion',
            index=models.Index(fields=['package', 'question_type'], name='games_lette_package_fb43db_idx'),
        ),
    ]
