# Generated by Django 5.2.4 on 2025-08-16 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_alter_gamesession_host_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeTrialUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('letters', 'Letters')], default='letters', max_length=32)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='gamesession',
            name='purchase',
            field=models.OneToOneField(blank=True, help_text='الشراء المرتبط بهذه الجلسة (إن وُجد)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='game_session', to='games.userpurchase'),
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['package', 'is_active'], name='games_games_package_7889ec_idx'),
        ),
        migrations.AddField(
            model_name='freetrialusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_trials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='freetrialusage',
            index=models.Index(fields=['user', 'game_type'], name='games_freet_user_id_f6c354_idx'),
        ),
        migrations.AddConstraint(
            model_name='freetrialusage',
            constraint=models.UniqueConstraint(fields=('user', 'game_type'), name='unique_free_trial_per_user_game'),
        ),
    ]
