# Generated by Django 5.2.4 on 2025-08-17 14:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_freetrialusage_gamesession_purchase_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contestant',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='gamepackage',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='lettersgamequestion',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='contestant',
            constraint=models.UniqueConstraint(fields=('session', 'name'), name='uniq_contestant_name_per_session'),
        ),
        migrations.AddConstraint(
            model_name='gamepackage',
            constraint=models.UniqueConstraint(fields=('game_type', 'package_number'), name='uniq_pkg_by_type_number'),
        ),
        migrations.AddConstraint(
            model_name='gamepackage',
            constraint=models.CheckConstraint(condition=models.Q(('is_free', False), ('price', Decimal('0.00')), _connector='OR'), name='free_pkg_price_must_be_zero'),
        ),
        migrations.AddConstraint(
            model_name='gamepackage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('discounted_price__isnull', True), ('original_price__isnull', True)), models.Q(('discounted_price__isnull', False), ('original_price__isnull', False), ('discounted_price__gt', Decimal('0.00')), ('original_price__gt', Decimal('0.00')), ('discounted_price__lt', models.F('original_price'))), _connector='OR'), name='valid_discount_relation'),
        ),
        migrations.AddConstraint(
            model_name='lettersgamequestion',
            constraint=models.UniqueConstraint(fields=('package', 'letter', 'question_type'), name='uniq_letter_qtype_per_pkg'),
        ),
    ]
