# Generated by Django 5.2.4 on 2025-08-18 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_alter_contestant_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freetrialusage',
            name='game_type',
            field=models.CharField(choices=[('letters', 'Letters'), ('images', 'Images')], default='letters', max_length=32),
        ),
        migrations.CreateModel(
            name='PictureGameProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_index', models.PositiveIntegerField(default=1)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='picture_progress', to='games.gamesession')),
            ],
            options={
                'indexes': [models.Index(fields=['session'], name='games_pictu_session_ad4802_idx')],
            },
        ),
        migrations.CreateModel(
            name='PictureRiddle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=1, help_text='ترتيب اللغز داخل الحزمة')),
                ('image_url', models.URLField(help_text='رابط الصورة (Cloudinary/سحابة)', max_length=500)),
                ('hint', models.CharField(blank=True, default='', help_text='تلميح يظهر للمقدم فقط', max_length=255)),
                ('answer', models.CharField(help_text='الإجابة الصحيحة', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picture_riddles', to='games.gamepackage')),
            ],
            options={
                'ordering': ('package', 'order'),
                'unique_together': {('package', 'order')},
            },
        ),
    ]
