# Generated by Django 5.2.4 on 2025-09-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_alter_freetrialusage_game_type_picturegameprogress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='team1_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='team2_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
