# Generated by Django 5.2.4 on 2025-09-12 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_alter_gamesession_team1_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamepackage',
            name='game_type',
            field=models.CharField(choices=[('letters', 'خلية الحروف'), ('images', 'تحدي الصور'), ('time', 'تحدّي الوقت'), ('quiz', 'سؤال وجواب')], help_text='اختر نوع اللعبة', max_length=20, verbose_name='نوع اللعبة'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='contestants_link',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='display_link',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='game_type',
            field=models.CharField(choices=[('letters', 'خلية الحروف'), ('images', 'تحدي الصور'), ('time', 'تحدّي الوقت'), ('quiz', 'سؤال وجواب')], max_length=20, verbose_name='نوع اللعبة'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='team1_name',
            field=models.CharField(default='الفريق الأخضر', max_length=50),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='team2_name',
            field=models.CharField(default='الفريق البرتقالي', max_length=50),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='winner_team',
            field=models.CharField(blank=True, choices=[('team1', 'الفريق الأول'), ('team2', 'الفريق الثاني'), ('draw', 'تعادل')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='TimeGameProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_index', models.PositiveIntegerField(default=1)),
                ('active_side', models.CharField(choices=[('A', 'اللاعب A'), ('B', 'اللاعب B')], default='A', max_length=1)),
                ('a_time_left_seconds', models.PositiveIntegerField(default=60)),
                ('b_time_left_seconds', models.PositiveIntegerField(default=60)),
                ('last_started_at', models.DateTimeField(blank=True, null=True)),
                ('is_running', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='time_progress', to='games.gamesession')),
            ],
            options={
                'verbose_name': 'تقدّم تحدّي الوقت',
                'verbose_name_plural': 'تقدّم تحدّي الوقت',
            },
        ),
        migrations.CreateModel(
            name='TimeRiddle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, help_text='ترتيب العرض داخل الباقة')),
                ('image_url', models.URLField(help_text='رابط الصورة', max_length=1000)),
                ('answer', models.CharField(help_text='الإجابة الصحيحة', max_length=200)),
                ('hint', models.CharField(blank=True, help_text='تلميح اختياري', max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_riddles', to='games.gamepackage')),
            ],
            options={
                'verbose_name': 'عنصر تحدّي الوقت',
                'verbose_name_plural': 'عناصر تحدّي الوقت',
                'ordering': ['order', 'id'],
                'unique_together': {('package', 'order')},
            },
        ),
    ]
