# Generated by Django 5.2.4 on 2025-09-13 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_alter_gamepackage_game_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('is_free_category', models.BooleanField(default=False, help_text='فئة تجربة (يجب أن تحتوي الحزمة #0 فقط)')),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('cover_image', models.URLField(blank=True, default='', help_text='صورة الغلاف في الواجهة')),
            ],
            options={
                'verbose_name': 'تصنيف تحدّي الوقت',
                'verbose_name_plural': 'تصنيفات تحدّي الوقت',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='TimePlayHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'سجل لعب (تحدّي الوقت)',
                'verbose_name_plural': 'سجل اللعب (تحدّي الوقت)',
                'ordering': ('-played_at',),
            },
        ),
        migrations.CreateModel(
            name='TimeSessionPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'حزمة جلسة (تحدّي الوقت)',
                'verbose_name_plural': 'حزم الجلسة (تحدّي الوقت)',
            },
        ),
        migrations.CreateModel(
            name='TimePackage',
            fields=[
            ],
            options={
                'verbose_name': 'حزمة - تحدّي الوقت',
                'verbose_name_plural': 'حزم - تحدّي الوقت',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('games.gamepackage',),
        ),
        migrations.RemoveConstraint(
            model_name='gamepackage',
            name='uniq_pkg_by_type_number',
        ),
        migrations.AlterField(
            model_name='gamepackage',
            name='package_number',
            field=models.IntegerField(help_text='رقم الحزمة (0 للتجريبية في فئات تحدّي الوقت، وإلا 1، 2، 3...)', verbose_name='رقم الحزمة'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='host',
            field=models.ForeignKey(blank=True, help_text='الشخص الذي ينظم اللعبة', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المقدم'),
        ),
        migrations.AlterField(
            model_name='lettersgameprogress',
            name='cell_states',
            field=models.JSONField(default=dict, verbose_name='حالة الخلايا'),
        ),
        migrations.AlterField(
            model_name='lettersgameprogress',
            name='used_letters',
            field=models.JSONField(default=list, verbose_name='الحروف المستخدمة'),
        ),
        migrations.AlterField(
            model_name='lettersgamequestion',
            name='answer',
            field=models.CharField(max_length=100, verbose_name='الإجابة'),
        ),
        migrations.AlterField(
            model_name='lettersgamequestion',
            name='category',
            field=models.CharField(max_length=50, verbose_name='التصنيف'),
        ),
        migrations.AlterField(
            model_name='lettersgamequestion',
            name='letter',
            field=models.CharField(max_length=3, verbose_name='الحرف'),
        ),
        migrations.AlterField(
            model_name='lettersgamequestion',
            name='question',
            field=models.TextField(verbose_name='السؤال'),
        ),
        migrations.AlterField(
            model_name='lettersgamequestion',
            name='question_type',
            field=models.CharField(choices=[('main', 'رئيسي'), ('alt1', 'بديل أول'), ('alt2', 'بديل ثاني'), ('alt3', 'بديل ثالث'), ('alt4', 'بديل رابع')], default='main', max_length=10, verbose_name='نوع السؤال'),
        ),
        migrations.AlterField(
            model_name='timeriddle',
            name='answer',
            field=models.CharField(help_text='الإجابة الصحيحة (تظهر للمقدّم فقط)', max_length=200),
        ),
        migrations.AlterField(
            model_name='timeriddle',
            name='hint',
            field=models.CharField(blank=True, help_text='تلميح اختياري (يظهر للمقدّم)', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userpurchase',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ينتهي في'),
        ),
        migrations.AlterField(
            model_name='userpurchase',
            name='games_played',
            field=models.IntegerField(default=0, verbose_name='عدد الألعاب'),
        ),
        migrations.AlterField(
            model_name='userpurchase',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='مكتملة؟'),
        ),
        migrations.AddField(
            model_name='gamepackage',
            name='time_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_packages', to='games.timecategory', verbose_name='تصنيف (تحدّي الوقت)'),
        ),
        migrations.AddIndex(
            model_name='gamepackage',
            index=models.Index(fields=['game_type', 'time_category', 'package_number'], name='games_gamep_game_ty_e0285a_idx'),
        ),
        migrations.AddConstraint(
            model_name='gamepackage',
            constraint=models.UniqueConstraint(condition=models.Q(('game_type', 'time')), fields=('time_category', 'package_number'), name='uniq_timepkg_per_category_number'),
        ),
        migrations.AddConstraint(
            model_name='gamepackage',
            constraint=models.UniqueConstraint(condition=models.Q(('game_type', 'time'), _negated=True), fields=('game_type', 'package_number'), name='uniq_pkg_by_type_number_except_time'),
        ),
        migrations.AddField(
            model_name='timeplayhistory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.timecategory'),
        ),
        migrations.AddField(
            model_name='timeplayhistory',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.gamepackage'),
        ),
        migrations.AddField(
            model_name='timeplayhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timesessionpackage',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.timecategory'),
        ),
        migrations.AddField(
            model_name='timesessionpackage',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.gamepackage'),
        ),
        migrations.AddField(
            model_name='timesessionpackage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_session_packages', to='games.gamesession'),
        ),
        migrations.AlterUniqueTogether(
            name='timeplayhistory',
            unique_together={('user', 'category', 'package')},
        ),
        migrations.AlterUniqueTogether(
            name='timesessionpackage',
            unique_together={('session', 'category')},
        ),
    ]
