# Generated by Django 5.2.4 on 2025-12-14 12:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_timecategory_timeplayhistory_timesessionpackage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamepackage',
            name='game_type',
            field=models.CharField(choices=[('letters', 'خلية الحروف'), ('images', 'تحدي الصور'), ('time', 'تحدّي الوقت'), ('quiz', 'سؤال وجواب'), ('imposter', 'لعبة امبوستر')], help_text='اختر نوع اللعبة', max_length=20, verbose_name='نوع اللعبة'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='game_type',
            field=models.CharField(choices=[('letters', 'خلية الحروف'), ('images', 'تحدي الصور'), ('time', 'تحدّي الوقت'), ('quiz', 'سؤال وجواب'), ('imposter', 'لعبة امبوستر')], max_length=20, verbose_name='نوع اللعبة'),
        ),
        migrations.CreateModel(
            name='ImposterWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='الكلمة الأساسية')),
                ('hint', models.CharField(blank=True, help_text='مجرد تلميح مبدئي تقدر تعرضه في الشرح أو تتجاهله في الواجهة.', max_length=200, verbose_name='تلميح مقترح (اختياري)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعّالة؟')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإضافة')),
                ('package', models.ForeignKey(limit_choices_to={'game_type': 'imposter'}, on_delete=django.db.models.deletion.CASCADE, related_name='imposter_words', to='games.gamepackage')),
            ],
            options={
                'verbose_name': 'كلمة امبوستر',
                'verbose_name_plural': 'كلمات امبوستر',
                'ordering': ('package', 'id'),
            },
        ),
    ]
