# Generated by Django 5.2.4 on 2026-01-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_alter_gamepackage_game_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImposterPackage',
            fields=[
            ],
            options={
                'verbose_name': 'حزمة - إمبوستر',
                'verbose_name_plural': 'حزم - إمبوستر',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('games.gamepackage',),
        ),
        migrations.AlterField(
            model_name='userpurchase',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='تم الدفع؟'),
        ),
    ]
