# Generated by Django 5.2.4 on 2026-02-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_imposterpackage_alter_userpurchase_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpurchase',
            name='is_gift',
            field=models.BooleanField(default=False, help_text='منحت هذه الحزمة كهدية بدون دفع', verbose_name='هدية؟'),
        ),
    ]
