# Generated by Django 5.2.4 on 2026-03-12 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0018_userpurchase_is_gift'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepackage',
            name='difficulty_level',
            field=models.CharField(choices=[('mixed', 'متنوعة الصعوبة'), ('easy', 'سهل'), ('medium', 'متوسط'), ('hard', 'صعب')], default='mixed', help_text='مستوى صعوبة الأسئلة في هذه الحزمة', max_length=10, verbose_name='مستوى الصعوبة'),
        ),
    ]
