# Generated by Django 5.2.4 on 2026-03-13 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0019_gamepackage_difficulty_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArabicOnlyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arabic_only_request', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'طلب عربي فقط',
                'verbose_name_plural': 'طلبات عربي فقط',
            },
        ),
    ]
