# Generated by Django 5.2.4 on 2026-03-14 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0020_arabic_only_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='lettersgamequestion',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'سهل'), ('medium', 'متوسط'), ('hard', 'صعب'), ('unspecified', 'غير محدد')], default='unspecified', max_length=15, verbose_name='مستوى الصعوبة'),
        ),
        migrations.AlterField(
            model_name='lettersgamequestion',
            name='category',
            field=models.CharField(blank=True, choices=[('general', 'الثقافة العامة'), ('religious', 'ديني'), ('science', 'العلوم'), ('geography', 'الجغرافيا'), ('arabic', 'اللغة العربية'), ('history', 'التاريخ'), ('who_said', 'من القائل ⚠️'), ('who_am_i', 'من أنا؟'), ('sports', 'الرياضة'), ('politics', 'السياسة')], default='', max_length=50, verbose_name='المجال'),
        ),
    ]
