# Generated by Django 5.2.4 on 2026-03-15 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0021_lettersgamequestion_difficulty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1_name', models.CharField(default='الفريق الأخضر', max_length=50, verbose_name='اسم الفريق الأول')),
                ('team2_name', models.CharField(default='الفريق البرتقالي', max_length=50, verbose_name='اسم الفريق الثاني')),
                ('team1_color', models.CharField(default='#22c55e', max_length=20, verbose_name='لون الفريق الأول')),
                ('team2_color', models.CharField(default='#f97316', max_length=20, verbose_name='لون الفريق الثاني')),
                ('grid_size', models.CharField(choices=[('3x3', '3×3 (9 خلايا)'), ('4x4', '4×4 (16 خلية)'), ('5x5', '5×5 (25 خلية) — افتراضي'), ('6x6', '6×6 (36 خلية)')], default='5x5', max_length=5, verbose_name='حجم الشبكة')),
                ('buzz_timer_seconds', models.PositiveIntegerField(default=3, help_text='المدة الافتراضية الموصى بها: 3 ثوانٍ', verbose_name='مدة قفل الزر (ثواني)')),
                ('penalty_timer_enabled', models.BooleanField(default=False, verbose_name='تفعيل مؤقت العقوبة')),
                ('penalty_timer_seconds', models.PositiveIntegerField(default=10, help_text='المدة الافتراضية الموصى بها: 10 ثوانٍ', verbose_name='مدة مؤقت العقوبة (ثواني)')),
                ('show_grid_to_contestants', models.BooleanField(default=False, verbose_name='إظهار الخلية للمتسابقين')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='games.gamesession', verbose_name='الجلسة')),
            ],
            options={
                'verbose_name': 'إعدادات الجلسة',
                'verbose_name_plural': 'إعدادات الجلسات',
            },
        ),
    ]
