# Generated by Django 5.2.4 on 2026-03-16 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0022_gamesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesettings',
            name='grid_size',
            field=models.CharField(choices=[('3x3', '3×3 (9 خلايا)'), ('4x4', '4×4 (16 خلية)'), ('5x5', '5×5 (25 خلية) — افتراضي'), ('6x6', '6×6 (36 خلية)'), ('7x7', '7×7 (49 خلية)')], default='5x5', max_length=5, verbose_name='حجم الشبكة'),
        ),
    ]
