# Generated by Django 5.2.4 on 2026-03-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0023_alter_gamesettings_grid_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesettings',
            name='show_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='show_subtitle',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
