# Generated by Django 5.2.4 on 2026-03-17 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0024_gamesettings_show_name_gamesettings_show_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesettings',
            name='nohost_mode',
            field=models.BooleanField(default=False),
        ),
    ]
