# Generated by Django 5.2.4 on 2026-03-17 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0025_gamesettings_nohost_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesettings',
            name='nohost_allow_cell_color',
            field=models.BooleanField(default=True, verbose_name='السماح بتغيير لون الخلية'),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='nohost_hide_answer',
            field=models.BooleanField(default=True, verbose_name='إخفاء الإجابة كاملاً'),
        ),
    ]
