# Generated by Django 5.2.4 on 2026-03-18 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0026_gamesettings_nohost_allow_cell_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamepackage',
            name='game_type',
            field=models.CharField(choices=[('letters', 'خلية الحروف'), ('images', 'تحدي الصور'), ('time', 'تحدّي الوقت'), ('quiz', 'سؤال وجواب'), ('imposter', 'لعبة امبوستر'), ('feud', 'فاميلي فيود')], help_text='اختر نوع اللعبة', max_length=20, verbose_name='نوع اللعبة'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='game_type',
            field=models.CharField(choices=[('letters', 'خلية الحروف'), ('images', 'تحدي الصور'), ('time', 'تحدّي الوقت'), ('quiz', 'سؤال وجواب'), ('imposter', 'لعبة امبوستر'), ('feud', 'فاميلي فيود')], max_length=20, verbose_name='نوع اللعبة'),
        ),
        migrations.CreateModel(
            name='FamilyFeudProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_question_index', models.PositiveIntegerField(default=1, verbose_name='رقم السؤال الحالي')),
                ('phase', models.CharField(choices=[('waiting', 'انتظار'), ('question', 'عرض السؤال'), ('buzzer', 'الزر مفتوح'), ('team1_turn', 'دور الفريق الأول'), ('team2_turn', 'دور الفريق الثاني'), ('steal', 'محاولة السرقة'), ('award', 'إعطاء النقاط'), ('finished', 'انتهت اللعبة')], default='waiting', max_length=20, verbose_name='المرحلة الحالية')),
                ('controlling_team', models.CharField(blank=True, choices=[('team1', 'الفريق الأول'), ('team2', 'الفريق الثاني'), ('', 'لا أحد')], default='', max_length=10, verbose_name='الفريق المتحكم')),
                ('team1_strikes', models.PositiveIntegerField(default=0, verbose_name='أخطاء الفريق الأول')),
                ('team2_strikes', models.PositiveIntegerField(default=0, verbose_name='أخطاء الفريق الثاني')),
                ('round_points', models.PositiveIntegerField(default=0, verbose_name='نقاط الجولة الحالية')),
                ('revealed_answers', models.JSONField(default=list, verbose_name='الإجابات المكشوفة')),
                ('current_multiplier', models.PositiveIntegerField(default=1, verbose_name='المضاعف الحالي')),
                ('last_buzzer_name', models.CharField(blank=True, default='', max_length=50, verbose_name='آخر ضاغط على الزر')),
                ('last_buzzer_team', models.CharField(blank=True, default='', max_length=10, verbose_name='فريق آخر ضاغط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feud_progress', to='games.gamesession')),
            ],
            options={
                'verbose_name': 'تقدم فاميلي فيود',
                'verbose_name_plural': 'تقدم فاميلي فيود',
            },
        ),
        migrations.CreateModel(
            name='FamilyFeudQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, help_text='ترتيب السؤال داخل الحزمة')),
                ('question_text', models.TextField(verbose_name='نص السؤال')),
                ('multiplier', models.PositiveIntegerField(choices=[(1, 'عادي ×1'), (2, 'مضاعف ×2'), (3, 'ثلاثي ×3')], default=1, help_text='يمكن للمقدم تغييره أثناء اللعب', verbose_name='مضاعف النقاط')),
                ('package', models.ForeignKey(limit_choices_to={'game_type': 'feud'}, on_delete=django.db.models.deletion.CASCADE, related_name='feud_questions', to='games.gamepackage')),
            ],
            options={
                'verbose_name': 'سؤال فاميلي فيود',
                'verbose_name_plural': 'أسئلة فاميلي فيود',
                'ordering': ['package', 'order'],
            },
        ),
        migrations.CreateModel(
            name='FamilyFeudAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(help_text='1 = الأكثر شيوعاً', verbose_name='الترتيب')),
                ('text', models.CharField(max_length=200, verbose_name='نص الإجابة')),
                ('points', models.PositiveIntegerField(help_text='نقاط هذه الإجابة (مجموع كل الإجابات يفضل 100)', verbose_name='النقاط')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='games.familyfeudquestion', verbose_name='السؤال')),
            ],
            options={
                'verbose_name': 'إجابة فاميلي فيود',
                'verbose_name_plural': 'إجابات فاميلي فيود',
                'ordering': ['question', 'rank'],
            },
        ),
        migrations.AddIndex(
            model_name='familyfeudquestion',
            index=models.Index(fields=['package', 'order'], name='games_famil_package_fbbf1b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='familyfeudquestion',
            unique_together={('package', 'order')},
        ),
        migrations.AddIndex(
            model_name='familyfeudanswer',
            index=models.Index(fields=['question', 'rank'], name='games_famil_questio_aef70f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='familyfeudanswer',
            unique_together={('question', 'rank')},
        ),
    ]
