# Generated by Django 5.2.4 on 2026-03-18 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0027_alter_gamepackage_game_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeudPackage',
            fields=[
            ],
            options={
                'verbose_name': 'حزمة - فاميلي فيود',
                'verbose_name_plural': 'حزم - فاميلي فيود',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('games.gamepackage',),
        ),
    ]
