# Generated by Django 5.2.4 on 2026-03-27 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0028_feudpackage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='team1_name',
            field=models.CharField(default='الفريق الأول', max_length=50),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='team2_name',
            field=models.CharField(default='الفريق الثاني', max_length=50),
        ),
    ]
