# Generated by Django 5.2.4 on 2026-03-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0029_alter_gamesession_team1_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesettings',
            name='auto_host_mode',
            field=models.BooleanField(default=False, help_text='يتيح للمتسابقين كتابة إجاباتهم والتصحيح التلقائي', verbose_name='وضع المقدم الآلي'),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='auto_host_timer_seconds',
            field=models.PositiveIntegerField(default=10, help_text='الوقت المتاح للمتسابق لكتابة إجابته بعد ضغط الزر', verbose_name='مدة الإجابة (ثواني)'),
        ),
        migrations.AddField(
            model_name='lettersgamequestion',
            name='accepted_answers',
            field=models.JSONField(blank=True, default=list, help_text='قائمة بإجابات إضافية صحيحة (مفيد للكلمات الأجنبية المعربة)', verbose_name='إجابات بديلة مقبولة'),
        ),
        migrations.AddField(
            model_name='lettersgamequestion',
            name='answer_type',
            field=models.CharField(choices=[('arabic', 'عربي'), ('foreign', 'شبهة / كلمة أجنبية')], default='arabic', help_text='عربي = النظام يراعي الإملاء | شبهة = تنبيه للمتسابق بالدقة', max_length=10, verbose_name='نوع الإجابة'),
        ),
    ]
