# Generated by Django 5.2.4 on 2026-03-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0030_gamesettings_auto_host_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesettings',
            name='auto_host_smart_correction',
            field=models.BooleanField(default=True, help_text='يراعي أخطاء الهمزات والتاء المربوطة تلقائياً', verbose_name='المصحح الذكي للإملاء'),
        ),
    ]
