# Generated by Django 5.2.4 on 2026-03-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0031_gamesettings_auto_host_smart_correction'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesettings',
            name='typewriter_enabled',
            field=models.BooleanField(default=False, verbose_name='محاكاة المقدم البشري'),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='typewriter_speed',
            field=models.PositiveIntegerField(default=80, verbose_name='سرعة الظهور (ms)'),
        ),
        migrations.AlterField(
            model_name='lettersgamequestion',
            name='accepted_answers',
            field=models.JSONField(blank=True, default=list, help_text='اكتب الإجابات البديلة هكذا: ["إجابة1", "إجابة2"] — اتركه فارغاً هكذا [] إذا ما في بدائل', verbose_name='إجابات بديلة مقبولة'),
        ),
    ]
