# Generated by Django 5.2.4 on 2026-03-30 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0032_gamesettings_typewriter_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesettings',
            name='auto_host_speech_enabled',
            field=models.BooleanField(default=False, verbose_name='قراءة السؤال صوتياً'),
        ),
    ]
