# Generated by Django 5.2.4 on 2026-03-31 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0033_gamesettings_auto_host_speech_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='LettersCellCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم الفقرة')),
                ('emoji', models.CharField(max_length=10, verbose_name='الإيموجي')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّلة')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'فقرة خلية الحروف',
                'verbose_name_plural': 'فقرات خلية الحروف',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='allow_category_repeat',
            field=models.BooleanField(default=False, verbose_name='السماح بتكرار الفقرة'),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='enabled_categories',
            field=models.JSONField(blank=True, default=list, verbose_name='الفقرات المفعّلة'),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='enhanced_mode',
            field=models.BooleanField(default=False, verbose_name='خلية الحروف المطورة'),
        ),
        migrations.CreateModel(
            name='LettersCategoryQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, default='', verbose_name='السؤال')),
                ('answer', models.CharField(max_length=200, verbose_name='الإجابة')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_questions/', verbose_name='صورة (اختياري)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_questions', to='games.letterspackage', verbose_name='الحزمة')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='games.letterscellcategory', verbose_name='الفقرة')),
            ],
            options={
                'verbose_name': 'سؤال فقرة',
                'verbose_name_plural': 'أسئلة الفقرات',
                'ordering': ['order'],
            },
        ),
    ]
