# Generated by Django 5.2.4 on 2026-04-02 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0034_letterscellcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='letterscategoryquestion',
            name='accepted_answers',
            field=models.JSONField(blank=True, default=list, verbose_name='إجابات بديلة'),
        ),
        migrations.AddField(
            model_name='letterscellcategory',
            name='input_type',
            field=models.CharField(choices=[('text', 'سؤال نصي'), ('image', 'صورة')], default='text', max_length=10, verbose_name='نوع المحتوى'),
        ),
        migrations.AlterField(
            model_name='letterscategoryquestion',
            name='image',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='رابط الصورة'),
        ),
        migrations.AlterField(
            model_name='letterscategoryquestion',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_questions', to='games.gamepackage', verbose_name='الحزمة'),
        ),
    ]
