# Generated by Django 5.2.4 on 2026-04-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0035_letterscategoryquestion_accepted_answers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesettings',
            name='allow_category_repeat',
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='category_repeat_count',
            field=models.PositiveIntegerField(default=1, verbose_name='عدد ظهور كل فقرة'),
        ),
    ]
